/**
 * Country coverage for timezone search: ISO 3166-1 alpha-2 code → IANA zone ids,
 * ordered by prominence so a country query surfaces its principal zone first.
 *
 * Country display names come from `Intl.DisplayNames` at runtime; this table only
 * pins which zones belong to a country. Ids that the runtime does not support are
 * dropped when the search index is built, so entries here may lead the platform's
 * tz database without breaking search.
 */
export const COUNTRY_ZONES: Readonly<Record<string, readonly string[]>> = {
	AD: ['Europe/Andorra'],
	AE: ['Asia/Dubai'],
	AF: ['Asia/Kabul'],
	AG: ['America/Antigua'],
	AL: ['Europe/Tirane'],
	AM: ['Asia/Yerevan'],
	AO: ['Africa/Luanda'],
	AR: ['America/Argentina/Buenos_Aires'],
	AT: ['Europe/Vienna'],
	AU: [
		'Australia/Sydney',
		'Australia/Melbourne',
		'Australia/Brisbane',
		'Australia/Perth',
		'Australia/Adelaide',
		'Australia/Darwin',
		'Australia/Hobart'
	],
	AZ: ['Asia/Baku'],
	BA: ['Europe/Sarajevo'],
	BB: ['America/Barbados'],
	BD: ['Asia/Dhaka'],
	BE: ['Europe/Brussels'],
	BF: ['Africa/Ouagadougou'],
	BG: ['Europe/Sofia'],
	BH: ['Asia/Bahrain'],
	BI: ['Africa/Bujumbura'],
	BJ: ['Africa/Porto-Novo'],
	BM: ['Atlantic/Bermuda'],
	BN: ['Asia/Brunei'],
	BO: ['America/La_Paz'],
	BR: [
		'America/Sao_Paulo',
		'America/Manaus',
		'America/Fortaleza',
		'America/Recife',
		'America/Bahia',
		'America/Belem',
		'America/Cuiaba',
		'America/Rio_Branco'
	],
	BS: ['America/Nassau'],
	BT: ['Asia/Thimphu'],
	BW: ['Africa/Gaborone'],
	BY: ['Europe/Minsk'],
	BZ: ['America/Belize'],
	CA: [
		'America/Toronto',
		'America/Vancouver',
		'America/Edmonton',
		'America/Winnipeg',
		'America/Halifax',
		'America/Regina',
		'America/St_Johns'
	],
	CD: ['Africa/Kinshasa', 'Africa/Lubumbashi'],
	CF: ['Africa/Bangui'],
	CG: ['Africa/Brazzaville'],
	CH: ['Europe/Zurich'],
	CI: ['Africa/Abidjan'],
	CL: ['America/Santiago', 'Pacific/Easter'],
	CM: ['Africa/Douala'],
	CN: ['Asia/Shanghai', 'Asia/Urumqi'],
	CO: ['America/Bogota'],
	CR: ['America/Costa_Rica'],
	CU: ['America/Havana'],
	CV: ['Atlantic/Cape_Verde'],
	CY: ['Asia/Nicosia'],
	CZ: ['Europe/Prague'],
	DE: ['Europe/Berlin'],
	DJ: ['Africa/Djibouti'],
	DK: ['Europe/Copenhagen'],
	DO: ['America/Santo_Domingo'],
	DZ: ['Africa/Algiers'],
	EC: ['America/Guayaquil', 'Pacific/Galapagos'],
	EE: ['Europe/Tallinn'],
	EG: ['Africa/Cairo'],
	ER: ['Africa/Asmara'],
	ES: ['Europe/Madrid', 'Atlantic/Canary'],
	ET: ['Africa/Addis_Ababa'],
	FI: ['Europe/Helsinki'],
	FJ: ['Pacific/Fiji'],
	FM: ['Pacific/Pohnpei', 'Pacific/Chuuk'],
	FO: ['Atlantic/Faroe'],
	FR: ['Europe/Paris'],
	GA: ['Africa/Libreville'],
	GB: ['Europe/London'],
	GD: ['America/Grenada'],
	GE: ['Asia/Tbilisi'],
	GF: ['America/Cayenne'],
	GH: ['Africa/Accra'],
	GI: ['Europe/Gibraltar'],
	GL: ['America/Nuuk'],
	GM: ['Africa/Banjul'],
	GN: ['Africa/Conakry'],
	GP: ['America/Guadeloupe'],
	GQ: ['Africa/Malabo'],
	GR: ['Europe/Athens'],
	GT: ['America/Guatemala'],
	GU: ['Pacific/Guam'],
	GW: ['Africa/Bissau'],
	GY: ['America/Guyana'],
	HK: ['Asia/Hong_Kong'],
	HN: ['America/Tegucigalpa'],
	HR: ['Europe/Zagreb'],
	HT: ['America/Port-au-Prince'],
	HU: ['Europe/Budapest'],
	ID: ['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura'],
	IE: ['Europe/Dublin'],
	IL: ['Asia/Jerusalem'],
	IN: ['Asia/Kolkata'],
	IQ: ['Asia/Baghdad'],
	IR: ['Asia/Tehran'],
	IS: ['Atlantic/Reykjavik'],
	IT: ['Europe/Rome'],
	JM: ['America/Jamaica'],
	JO: ['Asia/Amman'],
	JP: ['Asia/Tokyo'],
	KE: ['Africa/Nairobi'],
	KG: ['Asia/Bishkek'],
	KH: ['Asia/Phnom_Penh'],
	KI: ['Pacific/Tarawa', 'Pacific/Kiritimati'],
	KM: ['Indian/Comoro'],
	KP: ['Asia/Pyongyang'],
	KR: ['Asia/Seoul'],
	KW: ['Asia/Kuwait'],
	KY: ['America/Cayman'],
	KZ: ['Asia/Almaty', 'Asia/Aqtobe'],
	LA: ['Asia/Vientiane'],
	LB: ['Asia/Beirut'],
	LI: ['Europe/Vaduz'],
	LK: ['Asia/Colombo'],
	LR: ['Africa/Monrovia'],
	LS: ['Africa/Maseru'],
	LT: ['Europe/Vilnius'],
	LU: ['Europe/Luxembourg'],
	LV: ['Europe/Riga'],
	LY: ['Africa/Tripoli'],
	MA: ['Africa/Casablanca'],
	MC: ['Europe/Monaco'],
	MD: ['Europe/Chisinau'],
	ME: ['Europe/Podgorica'],
	MG: ['Indian/Antananarivo'],
	MH: ['Pacific/Majuro'],
	MK: ['Europe/Skopje'],
	ML: ['Africa/Bamako'],
	MM: ['Asia/Yangon'],
	MN: ['Asia/Ulaanbaatar'],
	MO: ['Asia/Macau'],
	MQ: ['America/Martinique'],
	MR: ['Africa/Nouakchott'],
	MT: ['Europe/Malta'],
	MU: ['Indian/Mauritius'],
	MV: ['Indian/Maldives'],
	MW: ['Africa/Blantyre'],
	MX: [
		'America/Mexico_City',
		'America/Cancun',
		'America/Tijuana',
		'America/Monterrey',
		'America/Chihuahua',
		'America/Hermosillo',
		'America/Merida'
	],
	MY: ['Asia/Kuala_Lumpur', 'Asia/Kuching'],
	MZ: ['Africa/Maputo'],
	NA: ['Africa/Windhoek'],
	NC: ['Pacific/Noumea'],
	NE: ['Africa/Niamey'],
	NG: ['Africa/Lagos'],
	NI: ['America/Managua'],
	NL: ['Europe/Amsterdam'],
	NO: ['Europe/Oslo'],
	NP: ['Asia/Kathmandu'],
	NR: ['Pacific/Nauru'],
	NZ: ['Pacific/Auckland', 'Pacific/Chatham'],
	OM: ['Asia/Muscat'],
	PA: ['America/Panama'],
	PE: ['America/Lima'],
	PF: ['Pacific/Tahiti', 'Pacific/Marquesas'],
	PG: ['Pacific/Port_Moresby'],
	PH: ['Asia/Manila'],
	PK: ['Asia/Karachi'],
	PL: ['Europe/Warsaw'],
	PR: ['America/Puerto_Rico'],
	PS: ['Asia/Gaza', 'Asia/Hebron'],
	PT: ['Europe/Lisbon', 'Atlantic/Azores', 'Atlantic/Madeira'],
	PW: ['Pacific/Palau'],
	PY: ['America/Asuncion'],
	QA: ['Asia/Qatar'],
	RE: ['Indian/Reunion'],
	RO: ['Europe/Bucharest'],
	RS: ['Europe/Belgrade'],
	RU: [
		'Europe/Moscow',
		'Europe/Kaliningrad',
		'Europe/Samara',
		'Asia/Yekaterinburg',
		'Asia/Omsk',
		'Asia/Novosibirsk',
		'Asia/Krasnoyarsk',
		'Asia/Irkutsk',
		'Asia/Yakutsk',
		'Asia/Vladivostok',
		'Asia/Magadan',
		'Asia/Kamchatka'
	],
	RW: ['Africa/Kigali'],
	SA: ['Asia/Riyadh'],
	SB: ['Pacific/Guadalcanal'],
	SC: ['Indian/Mahe'],
	SD: ['Africa/Khartoum'],
	SE: ['Europe/Stockholm'],
	SG: ['Asia/Singapore'],
	SI: ['Europe/Ljubljana'],
	SK: ['Europe/Bratislava'],
	SL: ['Africa/Freetown'],
	SM: ['Europe/San_Marino'],
	SN: ['Africa/Dakar'],
	SO: ['Africa/Mogadishu'],
	SR: ['America/Paramaribo'],
	SS: ['Africa/Juba'],
	ST: ['Africa/Sao_Tome'],
	SV: ['America/El_Salvador'],
	SY: ['Asia/Damascus'],
	SZ: ['Africa/Mbabane'],
	TD: ['Africa/Ndjamena'],
	TG: ['Africa/Lome'],
	TH: ['Asia/Bangkok'],
	TJ: ['Asia/Dushanbe'],
	TL: ['Asia/Dili'],
	TM: ['Asia/Ashgabat'],
	TN: ['Africa/Tunis'],
	TO: ['Pacific/Tongatapu'],
	TR: ['Europe/Istanbul'],
	TT: ['America/Port_of_Spain'],
	TV: ['Pacific/Funafuti'],
	TW: ['Asia/Taipei'],
	TZ: ['Africa/Dar_es_Salaam'],
	UA: ['Europe/Kyiv'],
	UG: ['Africa/Kampala'],
	US: [
		'America/New_York',
		'America/Chicago',
		'America/Denver',
		'America/Los_Angeles',
		'America/Phoenix',
		'America/Anchorage',
		'Pacific/Honolulu',
		'America/Detroit'
	],
	UY: ['America/Montevideo'],
	UZ: ['Asia/Tashkent', 'Asia/Samarkand'],
	VE: ['America/Caracas'],
	VN: ['Asia/Ho_Chi_Minh'],
	VU: ['Pacific/Efate'],
	WS: ['Pacific/Apia'],
	YE: ['Asia/Aden'],
	ZA: ['Africa/Johannesburg'],
	ZM: ['Africa/Lusaka'],
	ZW: ['Africa/Harare']
};

/**
 * Names people type that `Intl.DisplayNames` does not produce for the code —
 * colloquial, historical, or abbreviated country names.
 */
export const COUNTRY_NAME_ALIASES: Readonly<Record<string, readonly string[]>> = {
	AE: ['uae', 'united arab emirates'],
	CD: ['drc', 'democratic republic of the congo'],
	CI: ['ivory coast'],
	CZ: ['czech republic'],
	GB: ['uk', 'united kingdom', 'great britain', 'britain', 'england', 'scotland', 'wales'],
	KR: ['korea'],
	MM: ['burma'],
	NL: ['holland'],
	TR: ['turkey'],
	US: ['usa', 'united states', 'united states of america'],
	VN: ['vietnam']
};
