export interface SQLiteMigrationManifestEntry {
  readonly migrationId: string;
  readonly schemaEpoch: number;
  readonly sequence: number;
  readonly dialect: 'sqlite';
  readonly artifact: URL;
  readonly checksumSha256: string;
  readonly atomicity: 'transactional';
  readonly dependsOn: null;
  readonly expectedApplicationFingerprint: string;
}

export interface SQLiteMigrationManifest {
  readonly formatVersion: 1;
  readonly runnerVersion: 1;
  readonly dialect: 'sqlite';
  readonly bootstrap: {
    readonly artifact: URL;
    readonly checksumSha256: string;
    readonly expectedRunnerFingerprint: string;
  };
  readonly migrations: readonly [SQLiteMigrationManifestEntry];
  readonly expectedEmptyApplicationFingerprint: string;
  readonly expectedCurrentFullFingerprint: string;
  readonly acceptedPredecessorLineages: readonly [];
}

// Fingerprints are filled from checked-in canonical snapshots generated by the
// deterministic snapshotter. Tests reject any artifact or schema drift.
export const SQLITE_MIGRATION_MANIFEST: SQLiteMigrationManifest = {
  formatVersion: 1,
  runnerVersion: 1,
  dialect: 'sqlite',
  bootstrap: {
    artifact: new URL('../../migrations/sqlite/schema_migrations.sql', import.meta.url),
    checksumSha256: '55548c37be3531717439c32b9ea00caa5eaa186c9ae3de54ad5ff7baa54f62e3',
    expectedRunnerFingerprint: '9792e3a7ea4c5705ec09f8f5f7b51e5d5bfeca700a30947dbe2e8c69b7cbeef5'
  },
  migrations: [{
    migrationId: 'e1_0001_identity_access',
    schemaEpoch: 1,
    sequence: 1,
    dialect: 'sqlite',
    artifact: new URL('../../migrations/sqlite/0001_identity_access.sql', import.meta.url),
    checksumSha256: '7bcc91ff77f3cb57b6d553dbf73546ec1d2972da24840d238d12323b7f50305c',
    atomicity: 'transactional',
    dependsOn: null,
    expectedApplicationFingerprint: 'a5c5c8d6a0894112ba7061ed02f7e2d8f527042c512a408b305d0a86248dd5db'
  }],
  expectedEmptyApplicationFingerprint: 'e3ded6858faee915d966f4bcaf5b768070aaaa4d5f1021ac04c713440106b89d',
  expectedCurrentFullFingerprint: 'bf528c0f84ba71ef2a218335be76ac962ec4b6343aa10e07e7f08ec36e680bb7',
  acceptedPredecessorLineages: []
};
